const CHECKOUT_MAX_ITEM_ROWS = 200;
const RESERVED_ORDER_STATUS = 'reserved';
const CHECKOUT_RESERVATION_TTL_MINUTES = Math.max(
    Number(process.env.CHECKOUT_RESERVATION_TTL_MINUTES || 45),
    30
);
const EXPIRED_RESERVATION_BATCH_SIZE = Math.max(
    Number(process.env.EXPIRED_RESERVATION_BATCH_SIZE || 100),
    25
);

module.exports = {
    CHECKOUT_MAX_ITEM_ROWS,
    RESERVED_ORDER_STATUS,
    CHECKOUT_RESERVATION_TTL_MINUTES,
    EXPIRED_RESERVATION_BATCH_SIZE
};
