const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');

require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const isProduction = process.env.NODE_ENV === 'production';

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: {
        rejectUnauthorized: true,
        ca: isProduction
            ? fs.readFileSync('/etc/secrets/supabase-ca.crt').toString()
            : fs.readFileSync(path.join(__dirname, '..', 'certs', 'supabase-ca.crt')).toString()
    }
});

const DAYS_MS = 24 * 60 * 60 * 1000;

const toIsoDate = (date) => {
    const year = date.getUTCFullYear();
    const month = String(date.getUTCMonth() + 1).padStart(2, '0');
    const day = String(date.getUTCDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
};

const buildFutureDate = (daysAhead) => {
    const date = new Date();
    date.setUTCHours(0, 0, 0, 0);
    date.setUTCDate(date.getUTCDate() + daysAhead);
    return toIsoDate(date);
};

const buildPastTimestamp = (daysAgo, hourUtc = 14) => {
    const timestamp = new Date(Date.now() - (daysAgo * DAYS_MS));
    timestamp.setUTCHours(hourUtc, 0, 0, 0);
    return timestamp.toISOString();
};

const hensSeed = [
    {
        name: 'Brown Ready-to-Lay Hens / Poules brunes prêtes à pondre',
        image_url: '/photos/hens_cropped.jpg',
        stock: 260
    },
    {
        name: 'White Ready-to-Lay Hens / Poules blanches prêtes à pondre',
        image_url: '/photos/white_hen.jpg',
        stock: 140
    },
    {
        name: 'Meat Chickens / Poulets à chair',
        image_url: '/photos/chicks_cropped.jpg',
        stock: 420
    },
    {
        name: 'Lamb / Agneau',
        image_url: '/photos/lamb_cropped.jpg',
        stock: 90
    }
];

const locations = ['hemmingford', 'bristol'];
const pickupDateOffsets = [14, 28, 42, 56];

const customersSeed = [
    {
        name: 'Alice Tremblay',
        phone: '5145551001',
        email: 'alice@dummy.local',
        address: '101 Maple Rd, Bristol'
    },
    {
        name: 'Marc Gagnon',
        phone: '4505551002',
        email: 'marc@dummy.local',
        address: '22 Chemin du Lac, Hemmingford'
    },
    {
        name: 'Sophie Roy',
        phone: '8195551003',
        email: 'sophie@dummy.local',
        address: '77 Rue Principale, Gatineau'
    },
    {
        name: 'David Smith',
        phone: '6135551004',
        email: 'david@dummy.local',
        address: '11 River St, Ottawa'
    },
    {
        name: 'Chloe Martin',
        phone: '4385551005',
        email: 'chloe@dummy.local',
        address: '58 Rue Saint-Jean, Montreal'
    }
];

const ensureSchema = async (client) => {
    await client.query('CREATE EXTENSION IF NOT EXISTS pgcrypto');

    await client.query(`
        CREATE TABLE IF NOT EXISTS hens (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            image_url TEXT,
            stock INTEGER NOT NULL DEFAULT 0,
            is_active BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        )
    `);
    await client.query(`
        CREATE UNIQUE INDEX IF NOT EXISTS hens_name_unique_idx
        ON hens (name)
    `);

    await client.query(`
        CREATE TABLE IF NOT EXISTS customers (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name TEXT NOT NULL,
            phone TEXT NOT NULL,
            email TEXT,
            address TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        )
    `);
    await client.query(`
        DO $$
        DECLARE
            phone_constraint_name TEXT;
        BEGIN
            SELECT tc.constraint_name
            INTO phone_constraint_name
            FROM information_schema.table_constraints tc
            INNER JOIN information_schema.key_column_usage kcu
                ON kcu.constraint_name = tc.constraint_name
               AND kcu.table_schema = tc.table_schema
               AND kcu.table_name = tc.table_name
            WHERE tc.table_schema = current_schema()
              AND tc.table_name = 'customers'
              AND tc.constraint_type = 'UNIQUE'
              AND kcu.column_name = 'phone'
            ORDER BY tc.constraint_name
            LIMIT 1;

            IF phone_constraint_name IS NOT NULL THEN
                EXECUTE format('ALTER TABLE customers DROP CONSTRAINT %I', phone_constraint_name);
            END IF;
        END $$;
    `);
    await client.query(`
        CREATE INDEX IF NOT EXISTS customers_phone_idx
        ON customers (phone)
    `);

    await client.query(`
        CREATE TABLE IF NOT EXISTS pickup_dates (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            date_value DATE NOT NULL,
            location TEXT NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        )
    `);
    await client.query(`
        CREATE UNIQUE INDEX IF NOT EXISTS pickup_dates_date_location_unique_idx
        ON pickup_dates (date_value, location)
    `);

    await client.query(`
        CREATE TABLE IF NOT EXISTS pickup_stock (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            pickup_date_id UUID NOT NULL REFERENCES pickup_dates(id) ON DELETE CASCADE,
            hen_id INTEGER NOT NULL REFERENCES hens(id) ON DELETE CASCADE,
            stock INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (pickup_date_id, hen_id)
        )
    `);

    await client.query(`
        CREATE SEQUENCE IF NOT EXISTS orders_order_number_seq
    `);

    await client.query(`
        CREATE TABLE IF NOT EXISTS orders (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            order_number BIGINT,
            customer_id UUID REFERENCES customers(id),
            customer_email TEXT,
            total_cents INTEGER NOT NULL DEFAULT 0,
            items JSONB NOT NULL DEFAULT '[]'::jsonb,
            status TEXT DEFAULT 'pending',
            pickup_date DATE,
            pickup_location TEXT,
            payment_type TEXT DEFAULT 'full',
            amount_paid_cents INTEGER,
            amount_due_cents INTEGER,
            language TEXT DEFAULT 'en',
            stripe_payment_id TEXT,
            confirmation_email_sent_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        )
    `);
    await client.query(`
        CREATE UNIQUE INDEX IF NOT EXISTS orders_order_number_unique_idx
        ON orders (order_number)
    `);
    await client.query(`
        CREATE OR REPLACE FUNCTION assign_order_number_for_active_order()
        RETURNS TRIGGER AS $$
        BEGIN
            IF TG_OP = 'UPDATE'
               AND OLD.order_number IS NOT NULL
               AND NEW.order_number IS DISTINCT FROM OLD.order_number THEN
                RAISE EXCEPTION 'order_number is immutable once assigned';
            END IF;

            IF NEW.order_number IS NULL THEN
                IF LOWER(COALESCE(NEW.status, 'pending')) NOT IN ('cancelled', 'reserved', 'archived') THEN
                    NEW.order_number := nextval('orders_order_number_seq');
                END IF;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    `);
    await client.query(`
        DROP TRIGGER IF EXISTS orders_assign_order_number_before_write ON orders
    `);
    await client.query(`
        CREATE TRIGGER orders_assign_order_number_before_write
        BEFORE INSERT OR UPDATE OF status, order_number
        ON orders
        FOR EACH ROW
        EXECUTE FUNCTION assign_order_number_for_active_order()
    `);
    await client.query(`
        CREATE INDEX IF NOT EXISTS orders_pickup_status_idx
        ON orders (pickup_date, pickup_location, LOWER(COALESCE(status, 'pending')))
    `);
};

const seedHens = async (client) => {
    const henByName = new Map();
    for (const hen of hensSeed) {
        const result = await client.query(
            `
            INSERT INTO hens (name, image_url, stock, is_active)
            VALUES ($1, $2, $3, true)
            ON CONFLICT (name) DO UPDATE
            SET image_url = EXCLUDED.image_url,
                stock = EXCLUDED.stock,
                is_active = true
            RETURNING id, name, stock
            `,
            [hen.name, hen.image_url, hen.stock]
        );
        henByName.set(hen.name, result.rows[0]);
    }
    return henByName;
};

const seedPickupDatesAndStock = async (client, henByName) => {
    const pickupDates = [];
    for (const daysAhead of pickupDateOffsets) {
        const dateValue = buildFutureDate(daysAhead);
        for (const location of locations) {
            const result = await client.query(
                `
                INSERT INTO pickup_dates (date_value, location, is_active)
                VALUES ($1, $2, true)
                ON CONFLICT (date_value, location) DO UPDATE
                SET is_active = true
                RETURNING id, date_value, location
                `,
                [dateValue, location]
            );
            pickupDates.push({
                ...result.rows[0],
                dateIndex: pickupDates.length
            });
        }
    }

    const hens = Array.from(henByName.values());
    for (let dateIdx = 0; dateIdx < pickupDates.length; dateIdx += 1) {
        const pickup = pickupDates[dateIdx];
        for (const hen of hens) {
            const isBristol = String(pickup.location).toLowerCase() === 'bristol';
            const baseline = Number(hen.stock || 0);
            const stock = Math.max(
                baseline - (dateIdx * 6) - (isBristol ? 12 : 0),
                0
            );
            await client.query(
                `
                INSERT INTO pickup_stock (pickup_date_id, hen_id, stock)
                VALUES ($1, $2, $3)
                ON CONFLICT (pickup_date_id, hen_id)
                DO UPDATE SET stock = EXCLUDED.stock
                `,
                [pickup.id, hen.id, stock]
            );
        }
    }

    return pickupDates;
};

const seedCustomers = async (client) => {
    const customerByEmail = new Map();
    for (const customer of customersSeed) {
        const result = await client.query(
            `
            INSERT INTO customers (name, phone, email, address)
            VALUES ($1, $2, $3, $4)
            ON CONFLICT (phone) DO UPDATE
            SET name = EXCLUDED.name,
                email = EXCLUDED.email,
                address = EXCLUDED.address
            RETURNING id, name, email
            `,
            [customer.name, customer.phone, customer.email, customer.address]
        );
        customerByEmail.set(customer.email, result.rows[0]);
    }
    return customerByEmail;
};

const buildLine = (hen, quantity, unitCents) => ({
    id: Number(hen.id),
    name: String(hen.name),
    quantity,
    unit_cents: unitCents,
    line_cents: unitCents * quantity
});

const seedOrders = async (client, { henByName, customerByEmail, pickupDates }) => {
    const existingDummy = await client.query(
        "SELECT COUNT(*)::int AS count FROM orders WHERE customer_email LIKE '%@dummy.local'"
    );
    if (Number(existingDummy.rows[0]?.count || 0) > 0) {
        return { inserted: 0, skipped: true };
    }

    const brownHen = henByName.get(hensSeed[0].name);
    const whiteHen = henByName.get(hensSeed[1].name);
    const meatHen = henByName.get(hensSeed[2].name);
    const lambHen = henByName.get(hensSeed[3].name);

    const pickup = pickupDates.map((entry) => ({
        date: toIsoDate(new Date(entry.date_value)),
        location: entry.location
    }));

    const ordersSeed = [
        {
            customerEmail: 'alice@dummy.local',
            status: 'reserved',
            pickup: pickup[0],
            paymentType: 'deposit',
            items: [buildLine(brownHen, 24, 1400), buildLine(meatHen, 15, 525)],
            createdAt: buildPastTimestamp(10),
            language: 'en'
        },
        {
            customerEmail: 'marc@dummy.local',
            status: 'paid',
            pickup: pickup[1],
            paymentType: 'full',
            items: [buildLine(whiteHen, 10, 1450)],
            createdAt: buildPastTimestamp(9),
            language: 'fr'
        },
        {
            customerEmail: 'sophie@dummy.local',
            status: 'pending',
            pickup: pickup[2],
            paymentType: 'deposit',
            items: [buildLine(brownHen, 30, 1300), buildLine(lambHen, 2, 42500)],
            createdAt: buildPastTimestamp(8),
            language: 'en'
        },
        {
            customerEmail: 'david@dummy.local',
            status: 'picked_up',
            pickup: pickup[3],
            paymentType: 'full',
            items: [buildLine(meatHen, 25, 500)],
            createdAt: buildPastTimestamp(7),
            language: 'en'
        },
        {
            customerEmail: 'chloe@dummy.local',
            status: 'cancelled',
            pickup: pickup[4],
            paymentType: 'full',
            items: [buildLine(whiteHen, 8, 1450)],
            createdAt: buildPastTimestamp(6),
            language: 'fr'
        },
        {
            customerEmail: 'alice@dummy.local',
            status: 'reserved',
            pickup: pickup[5],
            paymentType: 'deposit',
            items: [buildLine(brownHen, 18, 1400), buildLine(whiteHen, 6, 1450)],
            createdAt: buildPastTimestamp(5),
            language: 'en'
        },
        {
            customerEmail: 'marc@dummy.local',
            status: 'pending',
            pickup: pickup[6],
            paymentType: 'full',
            items: [buildLine(meatHen, 40, 475)],
            createdAt: buildPastTimestamp(4),
            language: 'fr'
        },
        {
            customerEmail: 'sophie@dummy.local',
            status: 'paid',
            pickup: pickup[7],
            paymentType: 'deposit',
            items: [buildLine(brownHen, 13, 1500), buildLine(lambHen, 1, 42500)],
            createdAt: buildPastTimestamp(3),
            language: 'en'
        }
    ];

    let inserted = 0;
    for (let i = 0; i < ordersSeed.length; i += 1) {
        const order = ordersSeed[i];
        const customer = customerByEmail.get(order.customerEmail);
        if (!customer) continue;

        const totalCents = order.items.reduce((sum, item) => sum + Number(item.line_cents || 0), 0);
        const isDeposit = order.paymentType === 'deposit';
        const amountPaidCents = isDeposit ? Math.floor(totalCents * 0.3) : totalCents;
        const amountDueCents = Math.max(totalCents - amountPaidCents, 0);

        await client.query(
            `
            INSERT INTO orders (
                customer_id,
                customer_email,
                total_cents,
                items,
                status,
                pickup_date,
                pickup_location,
                payment_type,
                amount_paid_cents,
                amount_due_cents,
                language,
                stripe_payment_id,
                created_at
            )
            VALUES (
                $1, $2, $3, $4::jsonb, $5, $6, $7, $8, $9, $10, $11, $12, $13
            )
            `,
            [
                customer.id,
                order.customerEmail,
                totalCents,
                JSON.stringify(order.items),
                order.status,
                order.pickup.date,
                order.pickup.location,
                order.paymentType,
                amountPaidCents,
                amountDueCents,
                order.language,
                `dummy_session_${i + 1}`,
                order.createdAt
            ]
        );
        inserted += 1;
    }

    return { inserted, skipped: false };
};

const printSummary = async (client) => {
    const [hens, dates, stocks, customers, orders] = await Promise.all([
        client.query('SELECT COUNT(*)::int AS count FROM hens'),
        client.query('SELECT COUNT(*)::int AS count FROM pickup_dates'),
        client.query('SELECT COUNT(*)::int AS count FROM pickup_stock'),
        client.query('SELECT COUNT(*)::int AS count FROM customers'),
        client.query('SELECT COUNT(*)::int AS count FROM orders')
    ]);

    console.log('Seed summary:');
    console.log(`- hens: ${hens.rows[0].count}`);
    console.log(`- pickup_dates: ${dates.rows[0].count}`);
    console.log(`- pickup_stock rows: ${stocks.rows[0].count}`);
    console.log(`- customers: ${customers.rows[0].count}`);
    console.log(`- orders: ${orders.rows[0].count}`);
};

async function run() {
    const client = await pool.connect();
    try {
        await client.query('BEGIN');
        await ensureSchema(client);
        const henByName = await seedHens(client);
        const pickupDates = await seedPickupDatesAndStock(client, henByName);
        const customerByEmail = await seedCustomers(client);
        const orderResult = await seedOrders(client, {
            henByName,
            customerByEmail,
            pickupDates
        });
        await client.query('COMMIT');

        if (orderResult.skipped) {
            console.log('Dummy orders already exist, skipped order inserts.');
        } else {
            console.log(`Inserted ${orderResult.inserted} dummy orders.`);
        }

        await printSummary(client);
    } catch (err) {
        await client.query('ROLLBACK');
        throw err;
    } finally {
        client.release();
        await pool.end();
    }
}

run().catch((err) => {
    console.error('Dummy data seed failed:', err);
    process.exit(1);
});
